# Description
# ===========
# This playbook create an Azure VM with public IP, and open 22 port for SSH

# Play One
# ===========
# Create Azure VM
- name: Play One -- Create Azure VM
  hosts: localhost
  vars:
    resource_group_name: mastery4
    vm_name: mastery4
    location: japaneast
    vm_user: azureuser
    deployment_name: myDeployment
  connection: local
  tasks:
  - name: Create a resource group
    azure_rm_resourcegroup:
      name: "{{ resource_group_name }}"
      location: "{{ location }}"
  - name: Create Azure deployment in Resource Group(Just Created Above)
    azure_rm_deployment:
      state: present
      resource_group_name: "{{ resource_group_name }}"
      name: "{{ deployment_name }}"
      location: "{{ location }}"
      template_link: 'https://raw.githubusercontent.com/NKStupid/azure-quickstart-templates/chenjian/101-vm-simple-rhel-unmanaged/azuredeploy.json'
      parameters:
        vmName:
          value: myFirstDeployment
        adminUsername:
          value: chenkiegcp2
        adminPasswordOrKey:
          value: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC69c3Z6HTUJ1ywmCoTGJuRVQwrw6NzWmeI3A37pvJLvFXOmkcQR0ILgY0b07F78mn0EgXYIjkjbBMIRS3IRlhd1JTWdsaG+vh3W7UCpBQ74VED29sxrLwcGZDlI5zmtVR0J4h9qjbf1TBWWPoEaj6QHeuM1T5tbfXW/wjE0OLMHzfxk2f4EuUZEllFaiCHI/wstxuYwXJNn4Fa7xod9hQgLdFEsU1cg98r/ujVu4dUwR5MvIjWC+O+IlHW5/QoUiw5Hr6vvKrVsp4nrEb7ofVdk8nA8Gai9KPG2PgpVXnw7lcYICBYSQQMFA9xrT/ESNXTUSPPqEZld4R5Bw2VCI2p
    register: azure

  - name: Add new instance to host group
    add_host:
      hostname: "{{ item['ips'][0].public_ip }}"
      groupname: azure_vms
    loop: "{{ azure.deployment.instances }}"
# Play Two
# ===========
# Configure Azure VM
- name: Configure Azure VM -- Play Two
  hosts: azure_vms
  user: chenkiegcp2
  gather_facts: false
  become: yes
  tasks:
  - name: Wait for SSH to come up
    wait_for:
      port: 22
      timeout: 2000
      state: started
  - name: echo the hostname of the vm
    shell: hostname
  - name: Unarchive a file that needs to be downloaded (added in 2.0)
    unarchive:
      src: https://www-eu.apache.org/dist/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz
      dest: /usr/local/bin/
      remote_src: yes
  - name: /etc/yum.repos.d/jenkins.repo 
    get_url:
      url: http://pkg.jenkins.io/redhat-stable/jenkins.repo
      dest: /etc/yum.repos.d/jenkins.repo
  - name: Example action to import a key from a url
    rpm_key:
      state: present
      key: http://pkg.jenkins.io/redhat-stable/jenkins.io.key
  - name: install git openjdk and jenkins
    package:
      name:
        - java-1.8.0-openjdk
        - git
        - jenkins
      state: latest
  - name: JAVA_HOME and M2_HOME
    get_url:
      url: https://raw.githubusercontent.com/NKStupid/Tools/master/create-ansible-lab/.bash_profile
      dest: ~/
  - name: source .bash_profile of JAVA_HOME and M2_HOME
    action: shell source ~/.bash_profile
  - name: start jenkins
    service:
      name: jenkins
      enabled: true
      state: started
  - name: start firewalld services
    service:
      name: firewalld
      enabled: true
      state: started
  - name: open firewalld 80
    firewalld:
      service: http
      permanent: true
      state: enabled
      immediate: yes
  - name: open firewalld 8080
    firewalld:
      port: 8080/tcp
      permanent: true
      state: enabled
      immediate: yes
