# Description
# ===========
# This playbook creates an Application Gateway. The azure_rm_appgw module is available in v2.7. If you are using Ansible 2.5 or 2.6
# You need to run "ansible-galaxy install azure.azure_preview_modules" to install the role to get lastest Ansible modules.
# 1. create resource group
# 1. create virtual network
# 1. create subnet
# 1. create application gateway

---
- hosts: localhost
  tasks:
    - name: Prepare random postfix
      set_fact:
        rpfx: "{{ 1000 | random }}"
      run_once: yes

- hosts: localhost
# If you are using Ansible v2.7. Remove below two lines since azure_rm_appgw module is available in v2.7. 
  roles:
    - azure.azure_preview_modules
  vars:
    resource_group: "{{ resource_group_name }}"
    location: eastus
    vnet_name: ansiblevnetname
    subnet_name: ansiblesubnetname
    appgw_name: appgw{{ rpfx }}
    azure_subscription_id: "{{ lookup('env','AZURE_SUBSCRIPTION_ID') }}"
  tasks:
    - name: Create a resource group
      azure_rm_resourcegroup:
        name: "{{ resource_group }}"
        location: "{{ location }}"

    - name: Create a container with httpd image 
      azure_rm_containerinstance:
        resource_group: "{{ resource_group }}"
        name: "aci{{ resource_group | hash('md5') | truncate(7, True, '') }}"
        os_type: linux
        ip_address: public
        location: eastus
        ports:
          - 80
        containers:
          - name: mycontainer1
            image: httpd
            memory: 1.5
            ports:
              - 80
      register: ci_output_a

    - name: Create another container with httpd image 
      azure_rm_containerinstance:
        resource_group: "{{ resource_group }}"
        name: "aci{{ resource_group | hash('md5') | truncate(7, True, '') }}b"
        os_type: linux
        ip_address: public
        location: eastus
        ports:
          - 80
        containers:
          - name: mycontainer1
            image: httpd
            memory: 1.5
            ports:
              - 80
      register: ci_output_b

    - name: Dump first container instance output
      debug:
        var: ci_output_a

    - name: Dump second container instance output
      debug:
        var: ci_output_b

    - name: Create a virtual network
      azure_rm_virtualnetwork:
        name: "{{ vnet_name }}"
        resource_group: "{{ resource_group }}"
        address_prefixes_cidr:
            - 10.1.0.0/16
            - 172.100.0.0/16
        dns_servers:
            - 127.0.0.1
            - 127.0.0.2

    - name: Create a subnet
      azure_rm_subnet:
        name: "{{ subnet_name }}"
        virtual_network_name: "{{ vnet_name }}"
        resource_group: "{{ resource_group }}"
        address_prefix_cidr: 10.1.0.0/24
      register: subnet_output

    - name: Create a public IP address
      azure_rm_publicipaddress:
        resource_group: "{{ resource_group }}"
        allocation_method: Dynamic
        name: appgwpublicip
        domain_name_label: "{{ resource_group }}"
      register: pip_output

    - name: Dump Public IP output
      debug:
        var: pip_output

    - name: Create instance of Application Gateway
      azure_rm_appgw:
        resource_group: "{{ resource_group }}"
        name: "{{ appgw_name }}"
        sku:
          name: standard_small
          tier: standard
          capacity: 2
        gateway_ip_configurations:
          - subnet:
              id: "{{ subnet_output.state.id }}"
            name: app_gateway_ip_config
        frontend_ip_configurations:
          - public_ip_address: appgwpublicip
            name: sample_gateway_frontend_ip_config
        frontend_ports:
          - port: 80
            name: ag_frontend_port
        backend_address_pools:
          - backend_addresses:
              - ip_address: "{{ ci_output_a.ip_address }}"
              - ip_address: "{{ ci_output_b.ip_address }}"
            name: test_backend_address_pool
        backend_http_settings_collection:
          - port: 80
            protocol: http
            cookie_based_affinity: enabled
            name: sample_appgateway_http_settings
        http_listeners:
          - frontend_ip_configuration: sample_gateway_frontend_ip_config
            frontend_port: ag_frontend_port
            name: sample_http_listener
        request_routing_rules:
          - rule_type: Basic
            backend_address_pool: test_backend_address_pool
            backend_http_settings: sample_appgateway_http_settings
            http_listener: sample_http_listener
            name: rule1
      register: output
