# Description
# ===========
# This playbook create an Azure VM with public IP, and subnet in another resource group.
# This Script will create two resource group, defined by variables resource_group and resource_group_secondary. 
# Then it creates VM in resource_group and virtual network with defined subnets,nsg rules in resource_group_secondary.

- name: Create Azure VM
  hosts: localhost
  connection: local
  vars:
    resource_group: "{{ resource_group_name }}"
    resource_group_secondary: createvmsubnetin2ndrg2
    vm_name: testvm
    location: eastus
#  roles:
#    - Azure.azure_preview_modules
  tasks:
  - name: Create a resource group
    azure_rm_resourcegroup:
        name: "{{ resource_group }}"
        location: "{{ location }}"
  - name: Create secondary resource group
    azure_rm_resourcegroup:
        name: "{{ resource_group_secondary }}"
        location: "{{ location }}"
  - name: Create virtual network
    azure_rm_virtualnetwork:
      resource_group: "{{ resource_group_secondary }}"
      name: "{{ vm_name }}"
      address_prefixes: "10.0.0.0/16"
  - name: Add subnet
    azure_rm_subnet:
      resource_group: "{{ resource_group_secondary }}"
      name: "{{ vm_name }}"
      address_prefix: "10.0.1.0/24"
      virtual_network: "{{ vm_name }}"
  - name: Create VM
    azure_rm_virtualmachine:
      resource_group: "{{ resource_group }}"
      name: "{{ vm_name }}"
      vm_size: Standard_DS1_v2
      admin_username: azureuser
      admin_password: Password@123
      virtual_network_resource_group: "{{ resource_group_secondary }}"
      virtual_network_name: "{{ vm_name }}"
      subnet_name: "{{ vm_name }}"
      image:
        offer: UbuntuServer
        publisher: Canonical
        sku: 16.04-LTS
        version: latest
