# Description
# ===========
# This playbook create a PostgreSQL server and an instance of PostgreSQL Database

---
- hosts: localhost
  tasks:
    - name: Prepare random postfix
      set_fact:
        rpfx: "{{ 1000 | random }}"
      run_once: yes

- hosts: localhost
  roles:
    - Azure.azure_preview_modules
  vars:
    resource_group: "{{ resource_group_name }}"
    location: eastus
    postgresqlserver_name: postgresql{{ rpfx }}
    postgresqldb_name: sqldbtest
    admin_username: admxyz
    admin_password: Abcpasswordxyz12!
  tasks:
    - name: Create a resource group
      azure_rm_resourcegroup:
        name: "{{ resource_group }}"
        location: "{{ location }}"

    - name: Create PostgreSQL Server
      azure_rm_postgresqlserver:
        resource_group: "{{ resource_group }}"
        name: "{{ postgresqlserver_name }}"
        sku:
          name: GP_Gen4_2
          tier: GeneralPurpose
        location: "{{ location }}"
        enforce_ssl: True
        admin_username: "{{ admin_username }}"
        admin_password: "{{ admin_password }}"
        storage_mb: 51200

    - name: Create instance of PostgreSQL Database
      azure_rm_postgresqldatabase:
        resource_group: "{{ resource_group }}"
        server_name: "{{ postgresqlserver_name }}"
        name: "{{ postgresqldb_name }}"
