# Description
# ===========
# This playbook create a SQL server and an instance of SQL Database,
# azure_rm_sqlserver, azure_rm_sqldatabase module is not available in v2.4, but in azure_preview_modules role,
# so you need to run "ansible-galaxy install Azure.azure_preview_modules" to install the role to get lastest Ansible modules.

---
- hosts: localhost
  roles:
    - Azure.azure_preview_modules
  vars:
    resource_group: sqlcreate001
    location: eastus
    sqlserver_name: sqlansible001
    sqldb_name: sqldbtest
    admin_username: admxyz
    admin_password: Abcpasswordxyz12!
  tasks:
    - name: Create a resource group
      azure_rm_resourcegroup:
        name: "{{ resource_group }}"
        location: "{{ location }}"
    - name: Create SQL Server
      azure_rm_sqlserver:
        name: "{{sqlserver_name}}"
        resource_group: "{{resource_group}}"
        version: 12.0
        admin_username: "{{admin_username}}"
        admin_password: "{{admin_password}}"
    - name: Create instance of SQL Database
      azure_rm_sqldatabase:
        resource_group: "{{resource_group}}"
        server_name: "{{sqlserver_name}}"
        name: "{{sqldb_name}}"
