# Description
# ===========
# This playbook create an Azure VM with public IP, and open 22 port for SSH, and add ssh public key to the VM.
# This playbook create an Azure VM with public IP
# Change variables below to customize your VM deployment

- name: Create Azure VM
  hosts: localhost
  connection: local
  vars:
    resource_group: vmcreatessh
    vm_name: testvm
    location: eastus
    ssh_key: "ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEAsbjU002j16fMWZI7ks65dKPkxSQEnGaXvRe9SQGZ1zKZZsefbFmz8bFEC2EWO0W7iV/LbykzKx9G9M5KMPsiLVrUBVkeKa01yssTAbYoukE8sbiFCwWTtGQVxFXgsosKM6y7OIIt5rkNu/nwU9OSz+VP9poH2tK3FO6EdI4qks84SOnBkfWIJRLTz5mM3ISEYb4ghQnt74Y7gzQhf2kMKDa0T8GIa4HA/+LVqUHlvkyrRuWYYNC5sAoN91HGtsSferUekgm3b4Z6jQ9AV+xC39ylgoCfozI0T/dPRV2THsp6Fs/kHp8t/FnuQV9lgd8H1hxPlgPme1TN9L9NcSXYgQ== rsa-key-20180402"
  tasks:
  - name: Create a resource group
    azure_rm_resourcegroup:
        name: "{{ resource_group }}"
        location: "{{ location }}"
  - name: Create virtual network
    azure_rm_virtualnetwork:
      resource_group: "{{ resource_group }}"
      name: "{{ vm_name }}"
      address_prefixes: "10.0.0.0/16"
  - name: Add subnet
    azure_rm_subnet:
      resource_group: "{{ resource_group }}"
      name: "{{ vm_name }}"
      address_prefix: "10.0.1.0/24"
      virtual_network: "{{ vm_name }}"
  - name: Create public IP address
    azure_rm_publicipaddress:
      resource_group: "{{ resource_group }}"
      allocation_method: Static
      name: "{{ vm_name }}"
  - name: Create Network Security Group that allows SSH
    azure_rm_securitygroup:
      resource_group: "{{ resource_group }}"
      name: "{{ vm_name }}"
      rules:
        - name: SSH
          protocol: Tcp
          destination_port_range: 22
          access: Allow
          priority: 1001
          direction: Inbound
  - name: Create virtual network inteface card
    azure_rm_networkinterface:
      resource_group: "{{ resource_group }}"
      name: "{{ vm_name }}"
      virtual_network: "{{ vm_name }}"
      subnet: "{{ vm_name }}"
      public_ip_name: "{{ vm_name }}"
      security_group: "{{ vm_name }}"
  - name: Create VM
    azure_rm_virtualmachine:
      resource_group: "{{ resource_group }}"
      name: "{{ vm_name }}"
      vm_size: Standard_DS1_v2
      admin_username: azureuser
      ssh_password_enabled: false
      ssh_public_keys:
        - path: /home/azureuser/.ssh/authorized_keys
          key_data: "{{ ssh_key }}"
      network_interfaces: "{{ vm_name }}"
      image:
        offer: UbuntuServer
        publisher: Canonical
        sku: 16.04-LTS
        version: latest