

- name: query resource groups
  hosts: localhost
  connection: local

  tasks:
  - name: create Azure resource group
    azure_rm_resourcegroup_facts:
    register: output

  - name: delete all resource groups
    azure_rm_resourcegroup:
      name: "{{ item.name }}"
      force: yes
      state: absent
    with_items:
      - "{{ output.ansible_facts.azure_resourcegroups }}"
    when:
      - item.name.startswith('aci_create') or item.name.startswith('appgateway_create') or item.name.startswith('mysql_create') or item.name.startswith('create_virtualmachine') or item.name.startswith('keyvault_create') or item.name.startswith('networkinterface_with') or item.name.startswith('postgresql_create') or item.name.startswith('sql_create') or item.name.startswith('vm_create')
