# Description
# ===========
# This is helper task to delete test resource group

- name: delete test resource group
  hosts: localhost
  connection: local
  tasks:
  - name: delete test resource group
    azure_rm_resourcegroup:
      name: "{{ resource_group_name }}"
      force: True
      state: absent

  - name: delete second resource group
    azure_rm_resourcegroup:
      name: "{{ resource_group_name }}2nd"
      force: True
      state: absent