# Description
# ===========
# This playbook scales an AKS cluster -- update number of nodes from 2(if you use the aks_create.yml to create AKS cluster) to 3
# Change variables below to customize your AKS deployment.
# It also requires a valid service principal to scale AKS cluster, so fill:
# - client_id
# - client_secret
# This sample requires Ansible 2.6 

- name: Scale Azure Kubernetes Service
  hosts: localhost
  connection: local
  vars:
    resource_group: "{{ resource_group_name }}"
    location: eastus
    aks_name: myAKSCluster
    username: azureuser
    ssh_key: ssh-rsa AAAAB3Nza...
    client_id: "{{ lookup('env', 'AZURE_CLIENT_ID') }}"
    client_secret: "{{ lookup('env', 'AZURE_CLIENT_SECRET') }}"
  tasks:
  - name: Scale an existed Azure Container Services (AKS) cluster
    azure_rm_aks:
      name: "{{ aks_name }}"
      location: "{{ location }}"
      resource_group: "{{ resource_group }}"
      dns_prefix: "{{ aks_name }}"
      linux_profile:
        admin_username: "{{ username }}"
        ssh_key: "{{ ssh_key }}"
      service_principal:
        client_id: "{{ client_id }}"
        client_secret: "{{ client_secret }}"
      agent_pool_profiles:
        - name: default
          count: 3
          vm_size: Standard_D2_v2
