---
- hosts: localhost
  roles:
    - azure.azure_preview_modules 
  vars:
    resource_group: "{{ resource_group_name }}"
    resource_group_secondary: "{{ resource_group_name }}2"
    resource_name: mySubNet
    location: eastus
  tasks:
    - name: Create a resource group
      azure_rm_resourcegroup:
        name: "{{ resource_group }}"
        location: "{{ location }}"

    - name: Create security group
      azure_rm_securitygroup:
        resource_group: "{{ resource_group_secondary }}"
        name: "{{ resource_name }}"
        purge_rules: yes
        rules:
          - name: ALLOW_SSH
            protocol: Tcp
            destination_port_range: 22
            access: Allow
            priority: 100
            direction: Inbound

    - name: Create virtual network
      azure_rm_virtualnetwork:
        resource_group: "{{ resource_group }}"
        name: "{{ resource_name }}"
        address_prefixes: "10.10.0.0/16"

    - name: Add subnet
      azure_rm_subnet:
        resource_group: "{{ resource_group }}"
        name: "{{ resource_name }}"
        address_prefix: "10.10.0.0/24"
        virtual_network: "{{ resource_name }}"
        security_group_name:
          resource_group: "{{ resource_group_secondary }}"
          name: "{{ resource_name }}"
