# Description
# ===========
# Use this playbook to query all the resources in a given resource group.
# This sample requires Ansible 2.6 

---
- hosts: localhost
  vars:
    resource_group: resoure-group-name

  tasks:
    - name: Call REST API - Resources_ListByResourceGroup
      azure_rm_resource_facts:
        api_version: '2018-02-01'
        resource_group: "{{ resource_group }}"
        resource_type: resources
      register: output

    - debug:
        var: output
