- hosts: localhost
  vars:
    resource_group:
  tasks:

    - name: Call REST API - ManagedInstances_CreateOrUpdate
      azure_rm_resource:
        # url: /subscriptions/{{ lookup('env','AZURE_SUBSCRIPTION_ID') }}/resourceGroups/{resourceGroupName}/providers/Microsoft.Sql/managedInstances/{managedInstanceName}
        api_version: '2015-05-01-preview'
        resource_group: "{{ resource_group }}"
        provider: sql
        resource_type: managedinstances
        body:
          tags: 
            tagKey1: TagValue1
          location: Japan East
          sku: 
            name: CLS3
            tier: Standard
            capacity: 1
          properties: 
            fullyQualifiedDomainName: testinstance.database.windows.net
            administratorLogin: dummylogin
            administratorLoginPassword: Un53cuRE!
            subnetId: /subscriptions/20D7082A-0FC7-4468-82BD-542694D5042B/resourceGroups/testrg/providers/Microsoft.Network/virtualNetworks/vnet1/subnets/subnet1
            vCores: 8
            storageSizeInGB: 1024
            licenseType: Full
    