# Description
# ===========
# Use this playbook to scale up VMSS -- update number of VMs from 2 to 3.
# Use vmss-create playbook to create VMSS first
# This sample requires Ansible 2.6 

---
- hosts: localhost
  vars:
    resource_group: vmsstestrg
    vmss_name: vmsstest
  tasks: 
    - name: Get scaleset info
      azure_rm_virtualmachine_scaleset_facts:
        resource_group: "{{ resource_group }}"
        name: "{{ vmss_name }}"
        format: curated
      register: output_scaleset

    - name: Dump scaleset info
      debug:
        var: output_scaleset

    - name: Modify scaleset (Change capacity to 3)
      set_fact:
        body: "{{ output_scaleset.ansible_facts.azure_vmss[0] | combine({'capacity': 3}, recursive=True) }}"

    - name: Update something in that VMSS
      azure_rm_virtualmachine_scaleset: "{{ body }}"
