# Description
# ===========
# Use this playbook to 
# - git clone and build a sample hello world java app
# - Install tomcat on VMSS, 
# - then copy war file to VMSS.
# - start tomcat
#
# Use vmss-create playbook to create VMSS first
# This sample requires Ansible 2.6 
#
# Dependencies
# ============
# - maven on ansible host
# - git on ansible host

---
- hosts: localhost
  vars:
    resource_group: vmsstestrg
    scaleset_name: vmsstest
    loadbalancer_name: vmsstestlb
    admin_username: "{{ lookup('env','VMSS_ADMIN_USERNAME') }}"
    admin_password: "{{ lookup('env','VMSS_ADMIN_PASSWORD') }}"
    repo_url: https://github.com/spring-guides/gs-spring-boot.git
    workspace: ~/src/helloworld

  tasks:   
    - include: get-hosts-tasks.yml

    - name: Git Clone sample app
      git:
        repo: "{{ repo_url }}"
        dest: "{{ workspace }}"

    - name: Build sample app
      shell: mvn package chdir="{{ workspace }}/complete"

- name: Install Tomcat on Ubuntu 16.04
  hosts: scalesethosts
  become: yes
  vars:
    workspace: ~/src/helloworld
    admin_username: "{{ lookup('env','VMSS_ADMIN_USERNAME') }}"

  tasks:
  - name: Install Java JDK
    apt:
      name: default-jdk
      update_cache: yes


  - name: Copy app to Azure VM
    copy:
      src: "{{ workspace }}/complete/target/gs-spring-boot-0.1.0.jar"
      dest: "/home/{{ admin_username }}/helloworld.jar"
      force: yes
      mode: 0755

  - name: Start the app
    shell: java -jar "/home/{{ admin_username }}/helloworld.jar" 2>&1 &
