# Description
# ===========
# Use this playbook to test URL on all VMs in the scaleset.
# Use vmss-create and vmss-setup-tomcat playbooks to create VMSS and install Tomcat first
# This sample requires Ansible 2.6 

---
- hosts: localhost
  vars:
    resource_group: "{{ resource_group_name }}"
    scaleset_name: myTestVMSS
    loadbalancer_name: vmsstestlb
    admin_username: "{{ lookup('env','VMSS_ADMIN_USERNAME') }}"
    admin_password: "{{ lookup('env','VMSS_ADMIN_PASSWORD') }}"

  tasks:   
    - include: get-hosts-tasks.yml

- hosts: scalesethosts
  tasks: 
    - name: Try to access application on specific VM
      uri:
        url: http://127.0.0.1:8080/
        method: GET
      register: output

    - name: Dump output
      debug:
        var: output
