---
- hosts: localhost
  roles:
    - Azure.azure_preview_modules
  vars:
    resource_group: zimsvmssrg
    scaleset_name: zimsvmss

  tasks:
    - name: Get scaleset info using azure_rm_resource_facts
      azure_rm_resource_facts:
        resource_group: "{{ resource_group }}"
        provider: compute
        resource_type: virtualmachinescalesets
        resource_name: "{{ scaleset_name }}"
        api_version: "2017-12-01"
      register: scaleset

    - name: Dump scaleset before modification
      debug:
        var: scaleset

    - name: Modify scaleset (set upgradePolicy to Automatic and capacity to 3)
      set_fact:
        body: "{{ scaleset.response | combine({'properties': { 'upgradePolicy': { 'mode': 'Automatic' }}, 'sku': { 'capacity': scaleset.response[0].sku.capacity + 1 }
}, recursive=True) }}"

    - name: Dump scaleset for modification
      debug:
        var: body

    - name: Update scaleset info using azure_rm_resource
      azure_rm_resource:
        resource_group: "{{ resource_group }}"
        provider: compute
        resource_type: virtualmachinescalesets
        resource_name: "{{ scaleset_name }}"
        api_version: "2017-12-01"
        body: "{{ body }}"
